export {};
const globalBucket = globalThis as { __pajeTests?: Promise<void>[] };
globalBucket.__pajeTests = [];
await import("./git_sync_core_test.js");
await import("./git_tree_selection_test.js");
await import("./git_parallel_sync_test.js");
await import("./git_branch_service_test.js");
await import("./git_command_helpers_test.js");
await import("./git_command_select_server_test.js");
await import("./ssh_config_test.js");
await import("./ssh_manager_test.js");
await import("./logger_broker_test.js");
await import("./ssh_key_store_command_test.js");
await import("./ssh_key_overwrite_test.js");
await import("./logger_transports_test.js");
await import("./log_store_level_test.js");
await import("./tui_render_test.js");
await import("./tui_loading_screen_test.js");
await import("./tui_stack_overflow_test.js");
await import("./tui_menu_dashboard_test.js");
await import("./gitlab_web_key_test.js");
await import("./git_sync_auth_guard_test.js");
await import("./gitlab_personal_token_test.js");
await import("./git_sync_tree_render_test.js");
await import("./git_sync_summary_test.js");
await import("./git_ant_glob_filter_test.js");
await Promise.all(globalBucket.__pajeTests ?? []);
